name: resume_app
description: Mohau Khakhu - Ultimate Resume Portfolio

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11
  share_plus: ^7.0.1
  google_fonts: ^4.0.4
  animated_text_kit: ^4.2.2
  percent_indicator: ^4.0.0
  carousel_slider: ^4.2.1
  shimmer: ^2.0.0
  expandable: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true